# Generated by Django 3.1.3 on 2020-11-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_producto_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_fabricacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
