# Generated by Django 3.1.3 on 2020-11-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201114_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_fabricacion',
            new_name='fecha_ingreso',
        ),
    ]
