# Generated by Django 3.1.3 on 2020-11-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_auto_20201114_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='archivo',
            field=models.FileField(null=True, upload_to='productos'),
        ),
    ]
