# Generated by Django 3.1.3 on 2020-11-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitud_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
