# Generated by Django 3.1.3 on 2020-11-15 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_auto_20201114_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.tipo'),
        ),
    ]
